version: '3.8'

services:
  pets-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
    depends_on:
      postgres-pets:
        condition: service_healthy
    ports:
      - "5006:8080"  # Maps host port 5006 to container port 8080
    networks:
      - pets-network

  postgres-pets:
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${PETS_DB}
    ports:
      - "5438:5432"  # Maps host port 5438 to container port 5432
    volumes:
      - pets-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pets-network

networks:
  pets-network:

volumes:
  pets-data:
